import vanReducer, {
  setVanId,
  setOwnerId,
  setVanStep1Data,
  setVanStep2Data,
  setVanStep3Data,
  setVanStep4Data,
  setVanStep5Data,
  setVanStep6Data,
  setVanProgressData,
  resetVanState,
} from "../reducers/vanReducer";
import {
  createVanStep1,
  createVanStep2,
  createVanStep3,
  createVanStep4,
  createVanStep5,
  createVanStep6,
  getVanProgress,
  getVansList,
  getDealerOwners,
  getDealerOwnersList,
  getOwnerDetails,
  getDealerDashboard,
  getComponentsList,
  getVanReview,
  publishVan,
  getVanDetails,
} from "../actions/vanAction";

export {
  createVanStep1,
  createVanStep2,
  createVanStep3,
  createVanStep4,
  createVanStep5,
  createVanStep6,
  getVanProgress,
  getVansList,
  getDealerOwners,
  getDealerOwnersList,
  getOwnerDetails,
  getDealerDashboard,
  getComponentsList,
  getVanReview,
  publishVan,
  getVanDetails,
  setVanId,
  setOwnerId,
  setVanStep1Data,
  setVanStep2Data,
  setVanStep3Data,
  setVanStep4Data,
  setVanStep5Data,
  setVanStep6Data,
  setVanProgressData,
  resetVanState,
};
export default vanReducer;

